# Header
menu:
  Home: /
  # Categories: /categories
  Archives: /archives
  About: /aboutme
rss:
github: https://github.com/leeong

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- archive
- recent_posts
# - tag
- tagcloud
- links

# Links
links:
  github: https://github.com/leeong
  leeong: http://www.leeong.cn

# Miscellaneous
google_analytics:
favicon: /css/images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
